### Get Запрос Users
GET http://127.0.0.1:10001/users/
Content-Type: application/json

### Get Запрос Genres
GET http://127.0.0.1:10001/genres/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NDM0Njk4NTF9.3YmqKPaWAoMqHE603laau7CFGXbW247B-qVwdf0-Tgg

### Get Запрос Genres
GET http://127.0.0.1:10001/genres/19
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NDM0NTI5NTl9.CO4Iys4Ys-zYWJ7bAfEO43K4NzHqrVOtTMtJHy1vmJ0

### Get Запрос movies
GET http://127.0.0.1:10001/movies/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NDM0NTE5ODB9.1v18HkrjHLek5ieBRm0OLQBvYpo05cyecOPgObihysE

### Post Movies на добавление
POST http://127.0.0.1:10001/movies/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NDM0NTE5ODB9.1v18HkrjHLek5ieBRm0OLQBvYpo05cyecOPgObihysE

{
  "description": "Тест",
  "rating": 7.8,
  "title": "Тест",
  "trailer": "Тест",
  "year": 2022,
  "genre_id": 17,
  "director_id": 1
}

### Post Запрос на добавление
POST http://127.0.0.1:10001/genres/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NDM0NTM2Njd9.2qFk7v8c14LyUbuVWAaPbL1xdtPapicP_Ml1JQT8Ozo

{
  "name": "gentre_test"
}

### Delete
DELETE http://127.0.0.1:10001/genres/18
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NDM0NTM2Njd9.2qFk7v8c14LyUbuVWAaPbL1xdtPapicP_Ml1JQT8Ozo


### PUT
PUT http://127.0.0.1:10001/genres/18
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NDM0NTM2Njd9.2qFk7v8c14LyUbuVWAaPbL1xdtPapicP_Ml1JQT8Ozo
{
  "name": "gentre_test2"
}

###
POST http://127.0.0.1:10001/auth/
Content-Type: application/json

{
  "username": "vasya",
  "password": "my_little_pony"
}

###
POST http://127.0.0.1:10001/users/
Content-Type: application/json

{
  "username": "SkyUser1",
  "password": "eGGPtRKS51",
  "role": "user"
}

###Create User
POST http://127.0.0.1:10001/auth/
Content-Type: application/json

{
  "username": "SkyUser1",
  "password": "eGGPtRKS51"
}
###Get_tokens




PUT http://127.0.0.1:10001/auth/
Content-Type: application/json

{
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlNreVVzZXIxIiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTQ2ODE2NzB9.RZ_PUfjjsmYdalie9BhcidI8eAAw7AixtnHiGaAS4X4"
}





